- hosts: servers
  become: yes
  tasks:
    - ansible.builtin.include_tasks: onboarding_setup.yml
    - ansible.builtin.include_tasks: add_mdatp_repo.yml
    - name: Update Debian (apt)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Update RedHat (yum)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Install MDATP - Debian
      apt:
        name: mdatp
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install MDATP - RedHat
      yum:
        name: mdatp
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Debian - Setting Device Tag to MDE-Management
      ansible.builtin.shell:
        cmd: mdatp edr tag set --name GROUP --value 'MDE-Management'
      when: ansible_os_family == "Debian"

    - name: RedHat - Setting Device Tag to MDE-Management
      ansible.builtin.shell:
        cmd: mdatp edr tag set --name GROUP --value 'MDE-Management'
      when: ansible_os_family == "RedHat"