- hosts: servers
  become: true
  tasks:
    - name: Uninstall MDATP - Debian
      apt:
        name: mdatp
        state: absent
      when: ansible_os_family == "Debian"
    - name: Uninstall MDATP - RedHat
      yum:
        name: mdatp
        state: absent
      when: ansible_os_family == "RedHat"